PVP:
    ENTITY_ATTACK:
        - "{0}[{1}] {2}{0} was killed by {3}{0}''s {4}{0}."
        - "{0}[{1}] {3}{0} just killed {2}{0} with a {4}{0}."
    CUSTOM:
        - "{0}[{1}] {2}{0} killed himself."
        - "{0}[{1}] {2}{0} took a free teleport to the spawn, sans items."
        - "{0}[{1}] {2}{0} took the easy way out."
        - "{0}[{1}] {2}{0} died from a self inflicted /kill."
DEATH:
    ENTITY_ATTACK:
        - "{0}[{1}] {2}{0} was killed by {3}{0}."
        - "{0}[{1}] {2}{0} took on {3}{0} and lost."
        - "{0}[{1}] {2}{0} failed to defeat {3}{0}."
        - "{0}[{1}] {3}{0} sent {2}{0} back to the spawn."
        - "{0}[{1}] {3}{0} stole all of {2}{0}''s items."
        - "{0}[{1}] {2}{0} was no match for {3}{0}."
    DROWNING:
        - "{0}[{1}] {2}{0} couldn''t find nemo in time."
        - "{0}[{1}] {2}{0} is swimming with the fishes."
        - "{0}[{1}] {2}{0} took a long walk off a short pier."
        - "{0}[{1}] {2}{0} couldn't beat the world record for longest held breath."
        - "{0}[{1}] {2}{0} is now 100% water."
        - "{0}[{1}] {2}{0} couldn't find any sunken treasure ships."
        - "{0}[{1}] {2}{0} fell asleep in the tub."
        - "{0}[{1}] {2}{0} quenched their thirst."
        - "{0}[{1}] Water is now {2}{0}''s best friend."
    BLOCK_EXPLOSION:
        - "{0}[{1}] {2}{0} died in an explosion."
    CONTACT:
        - "{0}[{1}] {2}{0} successfully hugged a cactus. Hooray!"
        - "{0}[{1}] {2}{0} poked a cactus, but the cactus poked back."
        - "{0}[{1}] {2}{0} died to a cactus."
        - "{0}[{1}] {2}{0} tripped and fell onto a cactus."
    SUFFOCATION: 
        - "{0}[{1}] {2}{0} cannot not breathe when buried alive."
        - "{0}[{1}] {2}{0} was buried alive."
        - "{0}[{1}] {2}{0} was trapped in a cave in."
        - "{0}[{1}] A cave in trapped and killed {2}{0}."
    FALL: 
        - "{0}[{1}] {2}{0} wondered why the ground was rushing toward him..."
        - "{0}[{1}] The ground disappeared from under {2}{0}."
        - "{0}[{1}] {2}{0} fell to his death."
        - "{0}[{1}] {2}{0} didn't bring their parachute."
        - "{0}[{1}] {2}{0} forgot a parachute."
        - "{0}[{1}] {2}{0} took a misguided leap of faith."
    FIRE:
        - "{0}[{1}] {2}{0} died in a fire."
        - "{0}[{1}] {2}{0} forgot how to stop, drop, and roll."
        - "{0}[{1}] {2}{0} is not fire resistant."
        - "{0}[{1}] {2}{0} was burned alive."
        - "{0}[{1}] {2}{0} fell onto the barbecue."
        - "{0}[{1}] {2}{0} discovered fire."
        - "{0}[{1}] Did someone order a well done {2}{0}?"
    FIRE_TICK:
        - "{0}[{1}] {2}{0} couldn't find water quickly enough."
    LAVA:
        - "{0}[{1}] {2}{0} tried to reach the diamonds, but fell into the lava instead."
        - "{0}[{1}] The lava wouldn't stop chasing {2}{0}."
        - "{0}[{1}] {2}{0} now knows lava is not water."
        - "{0}[{1}] {2}{0} has become obsidian."
        - "{0}[{1}] {2}{0} fell into lava."
    ENTITY_EXPLOSION: #TNT
        - "{0}[{1}] KABLEWY! {2}{0} just died in an explosion!"
        - "{0}[{1}] {2}{0} combusted into a thousand tiny pieces."
        - "{0}[{1}] {2}{0} found that TNT they lost earlier."
        - "{0}[{1}] {2}{0} had a premature detonation."
    VOID:
        - "{0}[{1}] {2}{0} fell through the world."
        - "{0}[{1}] {2}{0} discovered bedrock isn't always solid."
NoCause:
    Unknown:
        - "{0}[{1}] {2}{0} died from unknown causes."

CreatureNames:
    CREEPER:
        - "a creeper"
        - "a cute creeper"
        - "an adorable creeper"
        - "a lonely creeper"
    GHAST:
        - "a frenzied ghast"
        - "a ghast"
    GIANT:
        - "a huge zombie"
        - "a giant"
    PIG_ZOMBIE:
        - "a zombie pigman"
    SKELETON:
        - "a skeleton"
        - "an undead archer"
    SLIME:
        - "an icky slime"
        - "a slime"
    SPIDER:
        - "a spider"
    WOLF:
        - "a wolf"
        - "an angry wolf"
        - "a hungry wolf"
    ZOMBIE:
        - "an undead zombie"
        - "a hungry zombie"
        - "a zombie"
