DEATH:
    UNKNOWN: #Not a DamageCause
        - "{0}[{1}] {2}{0} died from unknown causes."
    PVP: #Not a DamageCause
        - "{0}[{1}] {2}{0} was killed by {3}{0}''s {4}{0}."
        - "{0}[{1}] {3}{0} just killed {2}{0} with a {4}{0}."
    ENTITY_ATTACK:
        - "{0}[{1}] {2}{0} was killed by {3}{0}."
        - "{0}[{1}] {2}{0} took on {3}{0} and lost."
        - "{0}[{1}] {2}{0} failed to defeat {3}{0}."
        - "{0}[{1}] {3}{0} sent {2}{0} back to the spawn."
        - "{0}[{1}] {3}{0} stole all of {2}{0}''s items."
        - "{0}[{1}] {2}{0} was no match for {3}{0}."
    PROJECTILE:
        - "{0}[{1}] {2}{0} was shot by {3}{0}."
        - "{0}[{1}] {2}{0} took an arrow to the heart from {3}{0}."
        - "{0}[{1}] {3}{0} missed the apple and hit {2}{0}''s brain with an arrow."
        - "{0}[{1}] {2}{0} took an arrow to the knee from {3}{0}."
    DROWNING:
        - "{0}[{1}] {2}{0} couldn''t find nemo in time."
        - "{0}[{1}] {2}{0} is swimming with the fishes."
        - "{0}[{1}] {2}{0} took a long walk off a short pier."
        - "{0}[{1}] {2}{0} couldn''t beat the world record for longest held breath."
        - "{0}[{1}] {2}{0} is now 100% water."
        - "{0}[{1}] {2}{0} couldn''t find any sunken treasure ships."
        - "{0}[{1}] {2}{0} fell asleep in the tub."
        - "{0}[{1}] {2}{0} quenched their thirst."
        - "{0}[{1}] Water is now {2}{0}''s best friend."
        - "{0}[{1}] {2}{0} drowned."
        - "{0}[{1}] {2}{0} inhaled too much water."
        - "{0}[{1}] {2}{0} forgot their Respiration enchantment."
        - "{0}[{1}] {2}{0} now knows they cannot breath under water."
    BLOCK_EXPLOSION: #TNT, but also is fired for creepers :(
        - "{0}[{1}] KABLEWY! {2}{0} just died in an explosion!"
        - "{0}[{1}] {2}{0} combusted into a thousand tiny pieces."
        - "{0}[{1}] {2}{0} died in an explosion."
        - "{0}[{1}] All that is left of {2}{0} is a nice hole."
        - "{0}[{1}] KABOOM! {2}{0} was killed in an explosion."
    CONTACT:
        - "{0}[{1}] {2}{0} successfully hugged a cactus. Hooray!"
        - "{0}[{1}] {2}{0} poked a cactus, but the cactus poked back."
        - "{0}[{1}] {2}{0} died to a cactus."
        - "{0}[{1}] {2}{0} tripped and fell onto a cactus."
    STARVATION:
        - "{0}[{1}] {2}{0} starved to death."
        - "{0}[{1}] {2}{0} ran out of food."
        - "{0}[{1}] {2}{0} forgot to cook dinner."
        - "{0}[{1}] {2}{0} left home without eating breakfast."
    SUFFOCATION:
        - "{0}[{1}] {2}{0} cannot not breathe when buried alive."
        - "{0}[{1}] {2}{0} was buried alive."
        - "{0}[{1}] {2}{0} was trapped in a cave in."
        - "{0}[{1}] A cave in trapped and killed {2}{0}."
        - "{0}[{1}] {2}{0} suffocated."
    FALL:
        - "{0}[{1}] {2}{0} wondered why the ground was rushing toward them..."
        - "{0}[{1}] The ground disappeared from under {2}{0}."
        - "{0}[{1}] {2}{0} fell to their death."
        - "{0}[{1}] {2}{0} didn''t bring their parachute."
        - "{0}[{1}] {2}{0} forgot a parachute."
        - "{0}[{1}] {2}{0} took a misguided leap of faith."
    FIRE:
        - "{0}[{1}] {2}{0} died in a fire."
        - "{0}[{1}] {2}{0} forgot how to stop, drop, and roll."
        - "{0}[{1}] {2}{0} is not fire resistant."
        - "{0}[{1}] {2}{0} was burned alive."
        - "{0}[{1}] {2}{0} fell onto the barbecue."
        - "{0}[{1}] {2}{0} discovered fire."
        - "{0}[{1}] Did someone order a well done {2}{0}?"
        - "{0}[{1}] {2}{0} just got cooked."
        - "{0}[{1}] {2}{0} burned to death."
    FIRE_TICK:
        - "{0}[{1}] {2}{0} couldn''t find water quickly enough."
        - "{0}[{1}] {2}{0} burned to death."
        - "{0}[{1}] {2}{0} made it out of the fire but burned to death."
        - "{0}[{1}] {2}{0} is not fire proof."
    LAVA:
        - "{0}[{1}] {2}{0} tried to reach the diamonds, but fell into the lava instead."
        - "{0}[{1}] The lava wouldn''t stop chasing {2}{0}."
        - "{0}[{1}] {2}{0} now knows lava is not water."
        - "{0}[{1}] {2}{0} has become obsidian."
        - "{0}[{1}] {2}{0} fell into lava."
        - "{0}[{1}] {2}{0} took a nice hot lava bath."
        - "{0}[{1}] {2}{0} accidently slipped into the lava."
        - "{0}[{1}] {2}{0} died in lava."
    ENTITY_EXPLOSION: #Creeper? Doesn't seem to ever be called??
        - "{0}[{1}] KABLEWY! {2}{0} just got hugged a creeper"
    VOID:
        - "{0}[{1}] {2}{0} has fallen into the void."
        - "{0}[{1}] The void has claimed {2}{0}''s soul."
        - "{0}[{1}] {2}{0}'' and the void are now one."
    LIGHTNING:
        - "{0}[{1}] {2}{0} was struck by lightning."
    SUICIDE:
        - "{0}[{1}] {2}{0} killed themselves."
        - "{0}[{1}] {2}{0} decided to take a trip to the spawn, sans items."
        - "{0}[{1}] {2}{0} took the easy way out."
        - "{0}[{1}] {2}{0} ended their own life."
        - "{0}[{1}] {2}{0} committed suicide."
        - "{0}[{1}] {2}{0} died by their own hand."
        - "{0}[{1}] {2}{0} suicided."
        - "{0}[{1}] {2}{0} took their own life."

CREATURES:
    CraftCreeper:
        - "a creeper"
        - "a cute creeper"
        - "an adorable creeper"
        - "a lonely creeper"
        - "a sneaky creeper"
    CraftGhast:
        - "a frenzied ghast"
        - "a ghast"
        - "a ghast fireball"
        - "an angry ghast"
    CraftGiant:
        - "a HUGE zombie"
        - "a giant"
        - "a giant zombie"
    CraftPigZombie:
        - "a zombie pigman"
        - "a swarm of zombie pigmen"
        - "a hellish pigman"
    CraftSkeleton:
        - "a skeleton"
        - "an undead archer"
    CraftSlime:
        - "an icky slime"
        - "a slime"
        - "a green cube"
    CraftSpider:
        - "a spider"
        - "a large spider"
    CraftCaveSpider:
        - "a cave spider"
        - "a poisonous spider"
        - "a nest of spiders"
    CraftWolf:
        - "a wolf"
        - "an angry wolf"
        - "a hungry wolf"
    CraftZombie:
        - "an undead zombie"
        - "a hungry zombie"
        - "a zombie"
    CraftEnderman:
        - "an enderman"
        - "a lurking enderman"
        - "a stalking enderman"
        - "a shrouded enderman"
        - "a creepy enderman"
        - "a dark figure"
        - "a shadowy figure"
    CraftBlaze:
        - "a burning whirlwind"
        - "a flaming blaze"
        - "an angry blaze"
        - "a blazing blaze"
        - "a tornado of fire"
    CraftMagmaCube:
        - "a magma cube"
        - "a cube of magma"
    CraftEnderDragon:
        - "the Ender Dragon"
        - "a dragon"
        - "the black dragon"

ITEMS:
    AIR:
        - "bare fists"
        - "fists"
        - "knuckle sandwich"