DEATH:
    UNKNOWN: #Not a DamageCause
        - "{1}{0} died from unknown causes."
    PVP: #Not a DamageCause
        - "{1}{0} was killed by {2}{0}''s {3}{0}."
        - "{2}{0} just killed {1}{0} with a {3}{0}."
    PVP_WOLF: #Not a DamageCause
        - "{1}{0} was just eaten alive by {2}{0}''s wolf!"
        - "{2}{0}''s wolf just feasted on the flesh of {1}{0}."
        - "{2}{0}''s wolf won''t go hungry tonight thanks to {1}{0}."
    ENTITY_ATTACK:
        - "{1}{0} was killed by {2}{0}."
        - "{1}{0} took on {2}{0} and lost."
        - "{1}{0} failed to defeat {2}{0}."
        - "{2}{0} sent {1}{0} back to the spawn."
        - "{2}{0} stole all of {1}{0}''s items."
        - "{1}{0} was no match for {2}{0}."
    PROJECTILE:
        - "{1}{0} was shot by {2}{0}."
        - "{1}{0} took an arrow to the heart from {2}{0}."
        - "{2}{0} missed the apple and hit {1}{0}''s brain with an arrow."
        - "{1}{0} took an arrow to the knee from {2}{0}."
    DROWNING:
        - "{1}{0} couldn''t find nemo in time."
        - "{1}{0} is swimming with the fishes."
        - "{1}{0} took a long walk off a short pier."
        - "{1}{0} couldn''t beat the world record for longest held breath."
        - "{1}{0} is now 100% water."
        - "{1}{0} couldn''t find any sunken treasure ships."
        - "{1}{0} fell asleep in the tub."
        - "{1}{0} quenched their thirst."
        - "Water is now {1}{0}''s best friend."
        - "{1}{0} drowned."
        - "{1}{0} inhaled too much water."
        - "{1}{0} forgot their Respiration enchantment."
        - "{1}{0} now knows they cannot breath under water."
    BLOCK_EXPLOSION: #TNT, but also is fired for creepers :(
        - "KABLEWY! {1}{0} just died in an explosion!"
        - "{1}{0} combusted into a thousand tiny pieces."
        - "{1}{0} died in an explosion."
        - "All that is left of {1}{0} is a nice hole."
        - "KABOOM! {1}{0} was killed in an explosion."
    CONTACT:
        - "{1}{0} successfully hugged a cactus. Hooray!"
        - "{1}{0} poked a cactus, but the cactus poked back."
        - "{1}{0} died to a cactus."
        - "{1}{0} tripped and fell onto a cactus."
    STARVATION:
        - "{1}{0} starved to death."
        - "{1}{0} ran out of food."
        - "{1}{0} forgot to cook dinner."
        - "{1}{0} left home without eating breakfast."
    SUFFOCATION:
        - "{1}{0} cannot not breathe when buried alive."
        - "{1}{0} was buried alive."
        - "{1}{0} was trapped in a cave in."
        - "A cave in trapped and killed {1}{0}."
        - "{1}{0} suffocated."
    FALL:
        - "{1}{0} wondered why the ground was rushing toward them..."
        - "The ground disappeared from under {1}{0}."
        - "{1}{0} fell to their death."
        - "{1}{0} didn''t bring their parachute."
        - "{1}{0} forgot a parachute."
        - "{1}{0} took a misguided leap of faith."
    FIRE:
        - "{1}{0} died in a fire."
        - "{1}{0} forgot how to stop, drop, and roll."
        - "{1}{0} is not fire resistant."
        - "{1}{0} was burned alive."
        - "{1}{0} fell onto the barbecue."
        - "{1}{0} discovered fire."
        - "Did someone order a well done {1}{0}?"
        - "{1}{0} just got cooked."
        - "{1}{0} burned to death."
    FIRE_TICK:
        - "{1}{0} couldn''t find water quickly enough."
        - "{1}{0} burned to death."
        - "{1}{0} made it out of the fire but burned to death."
        - "{1}{0} is not fire proof."
    LAVA:
        - "{1}{0} tried to reach the diamonds, but fell into the lava instead."
        - "The lava wouldn''t stop chasing {1}{0}."
        - "{1}{0} now knows lava is not water."
        - "{1}{0} has become obsidian."
        - "{1}{0} fell into lava."
        - "{1}{0} took a nice hot lava bath."
        - "{1}{0} accidently slipped into the lava."
        - "{1}{0} died in lava."
    ENTITY_EXPLOSION: #Creeper
        - "KABLEWY! {1}{0} just got hugged by a creeper"
        - "Awww! {1}{0} made friends with a creeper"
        - "A creeper tried just wanted to hug {1}{0}..."
        - "A creeper and {1}{0} are best buds!"
        - "A creeper got a little too excited at the sight of {1}{0}."
    VOID:
        - "{1}{0} has fallen into the void."
        - "The void has claimed {1}{0}''s soul."
        - "{1}{0} and the void are now one."
    LIGHTNING:
        - "{1}{0} was struck by lightning."
    SUICIDE:
        - "{1}{0} killed themselves."
        - "{1}{0} decided to take a trip to the spawn, sans items."
        - "{1}{0} took the easy way out."
        - "{1}{0} ended their own life."
        - "{1}{0} committed suicide."
        - "{1}{0} died by their own hand."
        - "{1}{0} suicided."
        - "{1}{0} took their own life."
EXTERNAL:
    SAG_WIN: "{1}{0} defeated {2}{0} at Sand and Gravel!"
    SAG_TIE: "{1}{0} and {2}{0} tied in an epic match of Sand and Gravel!"
CREATURES:
    CraftCreeper:
        - "a creeper"
        - "a cute creeper"
        - "an adorable creeper"
        - "a lonely creeper"
        - "a sneaky creeper"
    CraftGhast:
        - "a frenzied ghast"
        - "a ghast"
        - "a ghast fireball"
        - "an angry ghast"
    CraftGiant:
        - "a HUGE zombie"
        - "a giant"
        - "a giant zombie"
    CraftPigZombie:
        - "a zombie pigman"
        - "a swarm of zombie pigmen"
        - "a hellish pigman"
    CraftSkeleton:
        - "a skeleton"
        - "an undead archer"
    CraftSlime:
        - "an icky slime"
        - "a slime"
        - "a green cube"
    CraftSpider:
        - "a spider"
        - "a large spider"
    CraftCaveSpider:
        - "a cave spider"
        - "a poisonous spider"
        - "a nest of spiders"
    CraftWolf:
        - "a wolf"
        - "an angry wolf"
        - "a hungry wolf"
    CraftZombie:
        - "an undead zombie"
        - "a hungry zombie"
        - "a zombie"
    CraftEnderman:
        - "an enderman"
        - "a lurking enderman"
        - "a stalking enderman"
        - "a shrouded enderman"
        - "a creepy enderman"
        - "a dark figure"
        - "a shadowy figure"
    CraftBlaze:
        - "a burning whirlwind"
        - "a flaming blaze"
        - "an angry blaze"
        - "a blazing blaze"
        - "a tornado of fire"
    CraftMagmaCube:
        - "a magma cube"
        - "a cube of magma"
    CraftEnderDragon:
        - "the Ender Dragon"
        - "a dragon"
        - "the black dragon"

ITEMS:
    AIR:
        - "bare fists"
        - "fists"
        - "knuckle sandwich"