name: TownCrier
main: com.minecarts.towncrier.TownCrier
version: 1.0.2
website: http://minecarts.com
author: Verrier
depend: [BarrensChat, ObjectData]
description: >
             Support plugin for server wide announcements